language: node_js
node_js: "node"
cache: npm

before_script:
  - mkdir -p ./test/assets/XQUTS ./test/assets/QT3TS
  - curl -L https://github.com/LeoWoerteler/QT3TS/archive/master.tar.gz | tar -xz -C ./test/assets/QT3TS --strip-components=1
  - curl -L https://github.com/LeoWoerteler/XQUTS/archive/master.tar.gz | tar -xz -C ./test/assets/XQUTS --strip-components=1
  - unzip -q test/assets/QT3TS/xqueryx.zip -d ./test/assets/QT3TS/

script:
    - timeout 600 xvfb-run -a npm run ci-test -- --reporter dot;
    - timeout 600 xvfb-run -a npm run ci-qt3tests -- --reporter dot;
    - timeout 600 xvfb-run -a npm run integrationtests -- --reporter dot;
    - timeout 600 xvfb-run -a npm run qt3tests -- --dist --reporter dot;
    - timeout 600 xvfb-run -a npm run qt3testsxqueryx -- --reporter dot;
    - timeout 600 xvfb-run -a npm run ci-xqutstests -- --reporter dot;
    - timeout 600 xvfb-run -a npm run xqutstestsxqueryx -- --reporter dot;

after_success: npm run coverage
