sudo: required

language: generic

services:
    - docker

before_install:
    - docker pull liones/fontoxml-docker-base-pipelines:latest
script:
    - docker run --volume=`pwd`:/fontoxpath -w /fontoxpath liones/fontoxml-docker-base-pipelines /bin/sh -c "npm install; timeout 10m xvfb-run -a npm run test --ci_mode; timeout 10m xvfb-run -a npm run test --integration_tests --ci_mode"
