image: liones/fontoxml-docker-pipelines-test:stable

clone:
    depth: 1

pipelines:
  default:
    - step:
        script:
            - npm set progress=false
            - npm set depth=0
            - npm install
            - timeout 10m xvfb-run -a npm run test --ci_mode
            - timeout 10m xvfb-run -a npm run test --integration_tests --ci_mode
