image: liones/fontoxml-docker-pipelines-test:latest

clone:
    depth: 1

pipelines:
  default:
    - step:
        script:
            - npm set progress=false
            - npm set depth=0
            - npm install
            - timeout 10m xvfb-run -a npm run test --ci_mode
            - timeout 10m xvfb-run -a npm run test --integration_tests --ci_mode
            - (umask 077; echo $BITBUCKET_SSH_KEY | base64 --decode > ~/.ssh/id_rsa)
